project:
  type: website
  resources:
  - "pdf/*.pdf"
format:
    html: 
      toc: true
      toc-depth: 2
      toc-location: right
      toc-title: '   '
      theme: 
        light: ember.scss
        dark: [ember.scss, slate]
      css: custom.scss
      self-contained: true
      grid: 
        sidebar-width: 350px
        body-width: 550px
        margin-width: 350px
        gutter-width: 2em
      prettyPDF-typst: true
lightbox: true
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
footnotes-hover: true
reference-location: document
citation-location: document
bibliography: https://api.citedrive.com/bib/42337c79-d127-4faa-8eda-51dbd9283c1e/references.bib?x=eyJpZCI6ICI0MjMzN2M3OS1kMTI3LTRmYWEtOGVkYS01MWRiZDkyODNjMWUiLCAidXNlciI6ICIxMTkxMiIsICJzaWduYXR1cmUiOiAiMzI1NzdiYmFlODMwMmM4MTkwOGJjZWIzYTY4OGMzNjBiNzI5OTc4ZGQ3MGM2M2QzNmE4MWI0ZWU5NzczNTBmNCJ9